const ADD_FAV = 'ADD_FAV';
const REMOVE_FAV = 'REMOVE_FAV';
const FILTER_CARDS = 'FILTER_CARDS'
const ORDER_CARDS = 'ORDER_CARDS'
const REMOVE_ALL = 'REMOVE_ALL'

export { ADD_FAV, REMOVE_FAV, REMOVE_ALL, FILTER_CARDS, ORDER_CARDS };